PROJ_NAME=chip8

# folders
SRC=./src
INCLUDE=./include
BUILD=./build

# files
C_SRC=$(wildcard $(SRC)/*.c)
H_SRC=$(wildcard $(INCLUDE)/*.h)
TARGET=$(BUILD)/chip8

# obj files
OBJ=$(subst .c,.o,$(subst $(SRC),$(BUILD),$(C_SRC)))

# compiler
CC=gcc
CC_FLAGS=-c -Wall -Wextra -Iinclude -MMD -MP
LD_FLAGS=-lm

# debug/release
BUILD_TYPE ?= debug
ifeq ($(BUILD_TYPE),debug)
	CC_FLAGS += -g -O0
else
	CC_FLAGS += -O2
endif

# SDL flags
SDL_CFLAGS=$(shell pkg-config --cflags sdl3)
SDL_LIBS=$(shell pkg-config --libs sdl3)

# dep files (auto-generated by -MMD)
DEP=$(OBJ:.o=.d)

all: $(TARGET)

$(TARGET): $(OBJ) | $(BUILD)
	$(CC) $^ $(SDL_LIBS) $(LD_FLAGS) -o $@

$(BUILD):
	mkdir $(BUILD) -p

$(BUILD)/%.o: $(SRC)/%.c | $(BUILD)
	$(CC) $< $(CC_FLAGS) $(SDL_CFLAGS) -o $@

-include $(DEP)

clean:
	@ rm -rf $(BUILD)

.PHONY: all clean
